#!/bin/bash

# from suckless tools ...

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

url="$(sed 's/.*│//g' | tr -d '\n' | # First remove linebreaks and mutt sidebars:
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

if [[ -z "$url" ]] ; then
    if [[ -n "$TMUX" ]] ; then
        tmux set-option -g display-time 1500
        tmux display-message "url: not valid"
        tmux set-option -g display-time 371
    else
        echo "url: not valid"
    fi
    exit 0
fi

if [[ -n "$TMUX" ]] ; then
    tmux set-option -g display-time 1500
    tmux display-message "url: $url"
    tmux set-option -g display-time 371
    sleep 2
fi

setsid xdg-open "$url" >/dev/null 2>&1 &
exit 0

